# PostgreSQL database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/airlinedb
spring.datasource.username=postgres
spring.datasource.password=1234

# Hibernate (ORM) settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Update schema automatically
spring.jpa.hibernate.ddl-auto=update

# Show SQL requests in console
spring.jpa.show-sql=true